/det/select Box

/vis/filtering/trajectories/create/chargeFilter
/vis/filtering/trajectories/chargeFilter-0/add 0
/vis/filtering/trajectories/chargeFilter-0/invert true
/vis/filtering/trajectories/chargeFilter-0/verbose false
/vis/filtering/trajectories/chargeFilter-0/active true

/vis/ogl/set/displayListLimit 1000000

/gen/select range

/gen/range/id 13
/gen/range/t0 0 ns
/gen/range/vertex 124.5 4.5 2 m
/gen/range/p_unit 0 0 -1

/gen/range/phi_min -0.2 rad 
/gen/range/phi_max  0.2 rad
/gen/range/eta_min -0.2
/gen/range/eta_max  0.2

/gen/range/p_mag {energy} GeV/c

/run/beamOn {count}
